services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Sidia2025
      POSTGRES_USER: vini
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: vinicius.loureiro.cavalcante12@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Sidia2025
    ports:
      - 8080:80

networks:
  default:
    name: postgres-network
    external: true